<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SGBR</RootNamespace>
    <PackageId>SGBR</PackageId>
    <Authors>Andrzej Jakuszyk</Authors>
    <Company>Squirrelistic Ltd</Company>
    <Copyright>Copyright (C) Squirrelistic Ltd</Copyright>
    <PackageProjectUrl>https://github.com/Squirrelistic/sgbr</PackageProjectUrl>
    <Product>Squirrelistic Google Books Reducer</Product>
    <Description>Reduces Google Books Files (Version 20200217) published by Google at https://storage.googleapis.com/books/ngrams/books/datasetsv3.html</Description>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestData\squirrel.gz">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>