name: sgbr

on:
  push:
    branches: [ "main", "upgrade-to-dotnet9" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: .NET Tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --configuration Release
      working-directory: sgbr.tests

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: .NET Tests
        path: "sgbr.tests/TestResults/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
